server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: 'http://localhost:3009'
          predicates:
            - Path=/api/customer/**
        - id: transaction-service
          uri: 'http://localhost:3004'
          predicates:
            - Path=/api/transaction/**
        - id: notif-service
          uri: 'http://localhost:3001'
          predicates:
            - Path=/api/notify/**